routes/web.php
<?php

/**
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', 'LanguageController');

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__.'/frontend/');
});

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     * These routes can not be hit if the password is expired
     */
    include_route_files(__DIR__.'/backend/');
});

app/Models/Standard/Traits/Attribute/StandardAttribute.php
<?php

namespace App\Models\Standard\Traits\Attribute;

/**
 * Trait RoleAttribute.
 */
trait StandardAttribute
{
    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        return '<a href="'.route('admin.standard.edit', $this).'" class="btn btn-primary"><i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'"></i></a>';
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        return '<a href="'.route('admin.standard.destroy', $this).'"
			 data-method="delete"
			 data-trans-button-cancel="'.__('buttons.general.cancel').'"
			 data-trans-button-confirm="'.__('buttons.general.crud.delete').'"
			 data-trans-title="'.__('strings.backend.general.are_you_sure').'"
			 class="btn btn-danger"><i class="fa fa-trash" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.delete').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        // if ($this->id == 1) {
        //     return 'N/A';
        // }

        return '<div class="btn-group btn-group-sm" customer="group" aria-label="User Actions">
			  '.$this->edit_button.'
			  '.$this->delete_button.'
			</div>';
    }
}

app/Http/Controllers/Backend/Chapter/ChapterController.php
<?php

namespace App\Http\Controllers\Backend\Chapter;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Chapter\Chapter;
use App\Models\Subject\Subject;
use App\Http\Requests\Backend\Chapter\StoreChapterRequest;
use App\Http\Requests\Backend\Chapter\UpdateChapterRequest;
use App\Http\Requests\Backend\Chapter\ManageChapterRequest;
use App\Repositories\Backend\Subject\SubjectRepository;
use App\Repositories\Backend\Standard\StandardRepository;
use App\Repositories\Backend\Chapter\ChapterRepository;
use App\Events\Backend\Chapter\ChapterCreated;
use App\Events\Backend\Chapter\ChapterUpdated;
use App\Events\Backend\Chapter\ChapterDeleted;


class ChapterController extends Controller
{
    protected $chapterRepository;
    protected $submodel;
    public function __construct(ChapterRepository $chapterRepository)
    {
        // $this->submodel = $standard;
        $this->chapterRepository = $chapterRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function index(Subject $subject,Chapter $chapter)
    {
        
          $chapters = $this->chapterRepository->getActivePaginated(25, 'id', 'asc');    
           return view('backend.chapter.index',compact('chapters'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Subject $subject, ChapterRepository $chapter)
    {
        
        $subjects=$subject->get();   
        $chapters=$this->chapterRepository->getActivePaginated(25, 'id', 'asc');
           return view('backend.chapter.create',compact('subjects','chapters'));       
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreChapterRequest $request)
    {
        
        // $this->subjectRepository->create($request->all());
        $this->chapterRepository->create($request->only(
            
            'chapter_name',
            'subject_id'
            
            )
        );
        return redirect()->route('admin.chapter.index')->withFlashSuccess(__('alerts.backend.subject.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
            //   return "<h1>Hello World!</h1>";

      return view('backend.Chapter.index')
      ->withSubject($this->topicRepository->getActivePaginated(25, 'id', 'asc'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject,Chapter $chapter)
    {
        $uniq_subject=$chapter->subject()->first();
        $subjects=$subject->get();
        return view('backend.chapter.edit', compact('uniq_subject','chapter','subjects'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Chapter $chapter,UpdateChapterRequest $request)
    {
        $this->chapterRepository->update($chapter, $request->only(
            'chapter_name',
            'subject_id'
            
        ));

        return redirect()->route('admin.chapter.index')->withFlashSuccess(__('alerts.backend.chapter.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Chapter $chapter)
    {
        $this->chapterRepository->deleteById($chapter->id);

        // event(new CustomerDeleted($customer));

        return redirect()->route('admin.chapter.index')->withFlashSuccess(__('alerts.backend.chapter.deleted'));
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

/**
 * Class DashboardController.
 */
class DashboardController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('backend.dashboard');
    }
}

app/Http/Controllers/Backend/Excel/ExcelController.php
<?php

namespace App\Http\Controllers\Backend\Excel;

use App\Http\Controllers\Controller;
// use Illuminate\Http\Request;
use App\Models\Standard\Standard;
use App\Models\Subject\Subject;
use App\Models\Chapter\Chapter;
use App\Models\Question\Question;
//use App\Repositories\Backend\Standard\StandardRepository;
 use App\Http\Requests\Backend\Excel\StoreExcelRequest;
 use App\Http\Requests\Backend\Excel\ManageExcelRequest;
//use App\Events\Backend\Standard\StandardCreated;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Session;
use Excel;
use File;
use Illuminate\Support\Facades\Input;

class ExcelController extends Controller
{
    protected $standard;
    protected $subject;
    protected $chapter;
    protected $question;
    public function  __construct(Standard $standard,Subject $subject,Chapter $chapter,Question $question)
    {
        $this->standard = $standard;
        $this->subject = $subject;
        $this->chapter = $chapter;
        $this->question = $question;

    }

    public function create()
    {
        return view('backend.excel.create');
    }

    public function store(Request $request)
    {
        if($request->hasFile('import_file')){
            Excel::load($request->file('import_file')->getRealPath(), function ($reader) {
                $recordMap = [];
                $currentStandard = null;
                $currentChapter = null;
                $currentSubject = null;
                $currentQuestion = null;
                $sid = null;
                $subjectId=null;
                $chapterId = null;
                foreach ($reader->toArray() as $key => $row) {

                    //check if current standard exists in db and get its ID
                     if($currentStandard != $row['standard_name']){
                        $standard = $this->standard->where('standard_name','=',$row['standard_name'])->first();
                        if($standard == null){
                            $data['standard_name'] = $row['standard_name'];
                            $standard = $this->standard->create($data);
                        }
                        $currentStandard = $standard->standard_name;
                        $sid= $standard->id;
                    }
                    

                               //check if current subject exists in db
                    if($currentSubject != $row['subject_name']){
                       $subject = $this->subject->where('standard_id','=',$sid)->where("subject_name","=",$row['subject_name'])->first();
                         if($subject == null){
                            $data['standard_id'] = $sid;
                            $data['subject_name'] = $row['subject_name'];
                             $subject = $this->subject->create($data);
                         }
                        $currentSubject = $subject->subject_name;
                        $subjectId= $subject->id;
                    } 
                        
                                //check if current chapter exists in db
                    if($currentChapter != $row['chapter_name']){
                    $chapter = $this->chapter->where('subject_id','=',$subjectId)->where('chapter_name','=',$row['chapter_name'])->first();
                        if($chapter == null){
                            $data['subject_id'] = $subjectId;
                            $data['chapter_name'] = $row['chapter_name'];
                            $chapter = $this->chapter->create($data);
                        }
                        $currentChapter = $chapter->chapter_name;
                        $chapterId= $chapter->id;    
                    } 
                        
                              //check if current Question exists in db
                      
                                $data['chapter_id'] = $chapterId;
                                $data['quest_name'] = $row['quest_name'];
                                $data['answer'] = $row['answer'];
                                $question = $this->question->create($data);
                            
                            
                           
                        
                }
            });
        }

        Session::put('success', 'Your file successfully import in database!!!');

        return back();
    }



}

app/Http/Controllers/Backend/Question/QuestionController.php
<?php

namespace App\Http\Controllers\Backend\Question;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Chapter\Chapter;
use App\Models\Videos\Videos;
use App\Models\Question\Question;
use App\Models\Standard\Standard;
use App\Models\Subject\Subject;
use App\Http\Requests\Backend\Question\StoreQuestionRequest;
use App\Http\Requests\Backend\Question\UpdateQuestionRequest;
use App\Http\Requests\Backend\Question\ManageQuestionRequest;
use App\Repositories\Backend\Question\QuestionRepository;
use App\Repositories\Backend\Chapter\ChapterRepository;
use App\Events\Backend\Question\QuestionCreated;
use App\Events\Backend\Question\QuestionUpdated;
use App\Events\Backend\Question\QuestionDeleted;
use DB;

class QuestionController extends Controller
{

    
    public function __construct(QuestionRepository $questionRepository)
    {
        
        $this->questionRepository = $questionRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function index(Question $question,Chapter $chapter)
    {
     
        
        $questions = $this->questionRepository->getActivePaginated(25, 'id', 'asc');    
        
           return view('backend.question.index',compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Chapter $chapter, Standard $standard,Subject $subject)
    {
        
        $chapters=$chapter->get();
        $standards=$standard->get();
        $subjects=$subject->get();
        $questions=$this->questionRepository->getActivePaginated(25, 'id', 'asc');
        
           return view('backend.question.create',compact('standards','subjects','chapters','questions'));


        
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreQuestionRequest $request)
    {
        
        // $this->subjectRepository->create($request->all());
        $this->questionRepository->create($request->only(
            
            'quest_name',
            'answer',
            'chapter_id'
            
            )
        );
        return redirect()->route('admin.question.index')->withFlashSuccess(__('alerts.backend.question.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
            //   return "<h1>Hello World!</h1>";

      return view('backend.question.index')
      ->withQuestion($this->questionRepository->getActivePaginated(25, 'id', 'asc'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Chapter $chapter,Question $question,Subject $subject,Standard $standard)
    {
        $posts = Subject::with('chapter')->get();
        $books = Subject::all();
        $uniq_standard=$subject->standard()->first();
        $uniq_subject=$subject->standard()->first();
        $uniq_chapter=$chapter->subject()->first();
        $chapters=$subject->get();
        $chapters=$chapter->get();
        $standards=$standard->get();
        $chapters=$chapter->get();
        return view('backend.question.edit', compact('standards','question','chapters','uniq_chapter'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Question $question,UpdatequestionRequest $request)
    {
        $this->questionRepository->update($question, $request->only(
            'quest_name',
            'answer',
            'chapter_id'
            
        ));

        return redirect()->route('admin.question.index')->withFlashSuccess(__('alerts.backend.question.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        $this->questionRepository->deleteById($question->id);

        // event(new CustomerDeleted($customer));

        return redirect()->route('admin.question.index')->withFlashSuccess(__('alerts.backend.question.deleted'));
    }

    public function subjectsdata($standard_id, Subject $subject){
        $subjects_data=$subject->where('standard_id','=',$standard_id)->get()->toJson();
       
        return $subjects_data;
    }

    public function chaptersdata($subject_id, Chapter $chapter){
        $chapters_data=$chapter->where('subject_id','=',$subject_id)->get()->toJson();
       
        return $chapters_data;
    }

    public function questionsdata($chapter_id, Question $question){
        $questions_data=$question->where('chapter_id','=',$chapter_id)->get()->toJson();
        return $questions_data;
    }
    public function videosdata($chapter_id, Videos $video){
        $videos_data=$video->where('chapter_id','=',$chapter_id)->get()->toJson();
        return $videos_data;
    }

    public function uniqvideo($uid, Videos $video){
        $uniqvideo=$video->where('id','=',$uid)->get()->toJson();
        
        return $uniqvideo;
    }

    public function qdata($q_id, Question $question){
        $data=$question->where('id','=',$q_id)->get()->toJson();
        return $data;
    }

    public function searchdata($term, Videos $video){
        $search_data=$video->where('title','like',$term.'%')->get()->toJson();
       
        return $search_data;
    }

    public function insertdata(Request $request){
        $id = DB::table('paper_infos')->insertGetId(
            ['standard' => $stand_text,
             'subject' => $subj_text,
             'chapter' => $chap_text,
             'school' => $school,
             'marks' => $marks,
             'paper_code' => $code,
             'year' => $year,]
        );

    foreach($question_text as $key => $value)
    {
        $lastinsert=DB::table('users')->insert([
        ['question' => $question_text[$key],
        'p_id' => $id[$key]]
        ]);
    }
    return response()->json(201);
    }


}

resources/views/backend/standard/change-password.blade.php
@extends ('backend.layouts.app')

@section ('title', __('labels.backend.access.users.management') . ' | ' . __('labels.backend.access.users.change_password'))

@section('breadcrumb-links')
    @include('backend.auth.user.includes.breadcrumb-links')
@endsection

@section('content')
{{ html()->form('PATCH', route('admin.auth.user.change-password.post', $user))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('labels.backend.access.users.management') }}
                        <small class="text-muted">{{ __('labels.backend.access.users.change_password') }}</small>
                    </h4>

                    <div class="small text-muted">
                        {{ __('labels.backend.access.users.change_password_for', ['user' => $user->name]) }}
                    </div>
                </div><!--col-->
            </div><!--row-->

            <hr />

            <div class="row mt-4 mb-4">
                <div class="col">
                    <div class="form-group row">
                        {{ html()->label(__('validation.attributes.backend.access.users.password'))->class('col-md-2 form-control-label')->for('password') }}

                        <div class="col-md-10">
                            {{ html()->password('password')
                                ->class('form-control')
                                ->placeholder( __('validation.attributes.backend.access.users.password'))
                                ->required()
                                ->autofocus() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                        {{ html()->label(__('validation.attributes.backend.access.users.password_confirmation'))->class('col-md-2 form-control-label')->for('password_confirmation') }}

                        <div class="col-md-10">
                            {{ html()->password('password_confirmation')
                                ->class('form-control')
                                ->placeholder( __('validation.attributes.backend.access.users.password_confirmation'))
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.auth.user.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.update')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->form()->close() }}
@endsection

resources/views/backend/standard/deactivated.blade.php
@extends ('backend.layouts.app')

@section ('title', __('labels.backend.access.users.management') . ' | ' . __('labels.backend.access.users.deactivated'))

@section('breadcrumb-links')
    @include('backend.auth.user.includes.breadcrumb-links')
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('labels.backend.access.users.management') }}
                    <small class="text-muted">{{ __('labels.backend.access.users.deactivated') }}</small>
                </h4>
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>{{ __('labels.backend.access.users.table.last_name') }}</th>
                            <th>{{ __('labels.backend.access.users.table.first_name') }}</th>
                            <th>{{ __('labels.backend.access.users.table.email') }}</th>
                            <th>{{ __('labels.backend.access.users.table.confirmed') }}</th>
                            <th>{{ __('labels.backend.access.users.table.roles') }}</th>
                            <th>{{ __('labels.backend.access.users.table.other_permissions') }}</th>
                            <th>{{ __('labels.backend.access.users.table.social') }}</th>
                            <th>{{ __('labels.backend.access.users.table.last_updated') }}</th>
                            <th>{{ __('labels.general.actions') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if ($users->count())
                            @foreach ($users as $user)
                                <tr>
                                    <td>{{ $user->last_name }}</td>
                                    <td>{{ $user->first_name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{!! $user->confirmed_label !!}</td>
                                    <td>{!! $user->roles_label !!}</td>
                                    <td>{!! $user->permissions_label !!}</td>
                                    <td>{!! $user->social_buttons !!}</td>
                                    <td>{{ $user->updated_at->diffForHumans() }}</td>
                                    <td>{!! $user->action_buttons !!}</td>
                                </tr>
                            @endforeach
                        @else
                            <tr><td colspan="9"><p class="text-center">{{ __('strings.backend.access.users.no_deactivated') }}</p></td></tr>
                        @endif
                        </tbody>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
        <div class="row">
            <div class="col-7">
                <div class="float-left">
                    {!! $users->total() !!} {{ trans_choice('labels.backend.access.users.table.total', $users->total()) }}
                </div>
            </div><!--col-->

            <div class="col-5">
                <div class="float-right">
                    {!! $users->render() !!}
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

resources/views/backend/standard/deleted.blade.php
@extends ('backend.layouts.app')

@section ('title', __('labels.backend.access.users.management') . ' | ' . __('labels.backend.access.users.deleted'))

@section('breadcrumb-links')
    @include('backend.auth.user.includes.breadcrumb-links')
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('labels.backend.access.users.management') }}
                    <small class="text-muted">{{ __('labels.backend.access.users.deleted') }}</small>
                </h4>
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>{{ __('labels.backend.access.users.table.last_name') }}</th>
                            <th>{{ __('labels.backend.access.users.table.first_name') }}</th>
                            <th>{{ __('labels.backend.access.users.table.email') }}</th>
                            <th>{{ __('labels.backend.access.users.table.confirmed') }}</th>
                            <th>{{ __('labels.backend.access.users.table.roles') }}</th>
                            <th>{{ __('labels.backend.access.users.table.other_permissions') }}</th>
                            <th>{{ __('labels.backend.access.users.table.social') }}</th>
                            <th>{{ __('labels.backend.access.users.table.last_updated') }}</th>
                            <th>{{ __('labels.general.actions') }}</th>
                        </tr>
                        </thead>
                        <tbody>

                        @if ($users->count())
                            @foreach ($users as $user)
                                <tr>
                                    <td>{{ $user->last_name }}</td>
                                    <td>{{ $user->first_name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{!! $user->confirmed_label !!}</td>
                                    <td>{!! $user->roles_label !!}</td>
                                    <td>{!! $user->permissions_label !!}</td>
                                    <td>{!! $user->social_buttons !!}</td>
                                    <td>{{ $user->updated_at->diffForHumans() }}</td>
                                    <td>{!! $user->action_buttons !!}</td>
                                </tr>
                            @endforeach
                        @else
                            <tr><td colspan="9"><p class="text-center">{{ __('strings.backend.access.users.no_deleted') }}</p></td></tr>
                        @endif
                        </tbody>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
        <div class="row">
            <div class="col-7">
                <div class="float-left">
                    {!! $users->total() !!} {{ trans_choice('labels.backend.access.users.table.total', $users->total()) }}
                </div>
            </div><!--col-->

            <div class="col-5">
                <div class="float-right">
                    {!! $users->render() !!}
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

resources/views/backend/standard/index.blade.php
@extends ('backend.layouts.app')

@section ('title', app_name() . ' | ' . __('labels.backend.access.standard.management'))



@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('labels.backend.access.standard.management') }} <small class="text-muted">{{ __('labels.backend.access.standard.active') }}</small>
                </h4>
            </div><!--col-->

            <div class="col-sm-7">
                @include('backend.standard.includes.header-buttons')
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>{{ __('labels.backend.access.standard.table.sno') }}</th>
                            <th>{{ __('labels.backend.access.standard.table.standard_name') }}</th>
                            
                            
                            <th>{{ __('labels.backend.access.standard.table.last_updated') }}</th>
                            <th>{{ __('labels.general.actions') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($standard as $standobj)
                            <tr>
                                <td>{{ $standobj->id }}</td>
                                <td>{{ $standobj->standard_name }}</td>
                                
                               
                                <td>{{ $standobj->updated_at->diffForHumans() }}</td>
                                <td>{!! $standobj->action_buttons !!}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
        <div class="row">
            <div class="col-7">
                <div class="float-left">
                    {!! $standard->total() !!} {{ trans_choice('labels.backend.access.standard.table.total', $standard->total()) }}
                </div>
            </div><!--col-->

            <div class="col-5">
                <div class="float-right">
                    {!! $standard->render() !!}
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection